### ISSUE TITLE
Event ordering

### ISSUE THREAD

**Issue by mrchechay** [mrchechay/mobileAppDev#7]
SQL bug, dates not appearing in order when querying database

**Comment by CharlesWatsonUK** [comment]
The dates are set as a text field, so i dont think you can do it with SQL. MySQLite has no date type just numeric, text and boolean I think. I think you will need to use java to do it.

**Comment by mrchechay** [comment]
Theres an SQL function date which formats strings to dates, its not working at the moment though, theres definitely a way to fix it
